### ISSUE TITLE
Cassandra commands not found

### ISSUE THREAD

**Issue by SanSiren** [kdcro101/vscode-cassandra#6]
Hey.
I use Visual Studio Code on Mac and installed your extension according to your documentation. Unfortunately it is not usable at all, since no command can be found (see screenshot). I tried all the normal things, restarting VSC, reinstalling, ...
Is there anything I am missing? Is the extension usable on Mac at all?
![screen shot 2019-02-06 at 4 10 51 pm](https://user-images.githubusercontent.com/2650171/52351110-56841300-2a2a-11e9-8885-d5056768dd66.png)
Best,
Britta

**Comment by pontnou** [comment]
Hi Britta,
I had the same problem, you have to create a workspace, save it, and try again to run "Cassandra Workbench: Generate configuration" command.
Good luck.
David

**Comment by Schenz** [comment]
I tried to create a workspace as well (even though I did in the past), but get command 'cassandraWorkbench.generateConfiguration' not found. Perhaps something changed in vs code version 1.32.3?

**Comment by dclough5** [comment]
I'm facing the same issue. I have an active workbench but get the same error. Has anyone solved this?

**Comment by dclough5** [comment]
I've just been able to generate a new configuration by right clicking in the workbench and selecting generate new configuration. From there you can edit the cluster info and attempt to connect.

**Comment by Tyri0n** [comment]
Same here. None of the extension's commands can be found.

From the developer console:

notificationsAlerts.ts:38 Error: command 'cassandraWorkbench.editConfiguration' not found
    at Proxy._tryExecuteCommand (commandService.ts:77)
    at r.then.i (commandService.ts:70)
    at process._tickCallback (internal/process/next_tick.js:68)
onDidNotificationChange	@	notificationsAlerts.ts:38
_register.model.onDidNotificationChange.e	@	notificationsAlerts.ts:26
fire	@	event.ts:558
addNotification	@	notifications.ts:156
error	@	notificationService.ts:51
telemetryActionsListener.value.toolBar.actionRunner.onDidRun.e	@	compositePart.ts:257
fire	@	event.ts:558
(anonymous)	@	actions.ts:201
a	@	errors.ts:184
_tickCallback	@	internal/process/next_tick.js:68
Promise.then (async)		
l	@	errors.ts:184
(anonymous)	@	errors.ts:184
n	@	errors.ts:184
run	@	actions.ts:190
onClick	@	menuEntryActionViewItem.ts:267
options.options.isMenu.i.setImmediate	@	actionbar.ts:138
runCallback	@	timers.js:694
tryOnImmediate	@	timers.js:665
processImmediate	@	timers.js:647

**Comment by Tyri0n** [comment]
Just installed on Windows and has same errors. I guess this isn't compatible with newer versions of VS Code.

abstractExtensionService.ts:390 Activating extension 'kdcro101.vscode-cassandra' failed: Cannot read property '0' of undefined.
_logMessageInConsole	@	abstractExtensionService.ts:390
console.ts:134 [Extension Host] Activating extension `kdcro101.vscode-cassandra` failed:  Cannot read property '0' of undefined
t.log	@	console.ts:134
console.ts:134 [Extension Host] Here is the error stack:  TypeError: Cannot read property '0' of undefined
	at module.exports.e.Workspace.getConfigurationRoot (c:\Users\xxx\.vscode\extensions\kdcro101.vscode-cassandra-0.3.6\packed\index.js:285:544123)
	at new module.exports.e.ConfigurationManager (c:\Users\xxx\.vscode\extensions\kdcro101.vscode-cassandra-0.3.6\packed\index.js:461:1025)
	at module.exports.e.activate (c:\Users\xxx\.vscode\extensions\kdcro101.vscode-cassandra-0.3.6\packed\index.js:468:4605)
	at Function._callActivateOptional (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:518)
	at Function._callActivate (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:207)
	at define._doActivateExtension.Promise.all.then.e (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:747:245)

**Comment by srfrnk** [comment]
After updating to a newer version of VSCode this extension seems to not be working at all.
- `command 'cassandraWorkbench.refresh' not found`
- `command 'cassandraWorkbench.revealPanel' not found`
- `command 'cassandraWorkbench.editConfiguration' not found`

Note that:
- I am using a workspace.
- I have used this extension in the past on this system.
- I can `curl` 9042 and reach cassandra from terminal.

**Comment by massinlaaouaj** [comment]
Same issue:

command 'cassandraWorkbench.editConfiguration' not found

**Comment by RamonFelipe** [comment]
Same issue:

* command 'cassandraWorkbench.editConfiguration' not found
* command 'cassandraWorkbench.generateConfiguration' not found

**Comment by phpash** [comment]
After installation Cassandra Workbench I had the same problem.
I needed to do:

Open workspace (workspace path is needed for configuration to generate), activate extension by running command from palette Cassandra Workbench: Generate configuration. This will generate .cassandraWorkbench.jsonc configuration file.

It is resolve for my issues

**Comment by talalhallaj68** [comment]
1. File -> add Folder to workspace... , then press add
2. Choose  view - > Command Palette .. then type or choose "Cassandra Workbench: Generate configuration"

**Comment by codexponent** [comment]
I also had the same issue
The problem: There was no Cassandra Workbench configuration file so to generate the file
1) Open the workspace (any will do)
2) Go to command Palette(Ctrl+Shift+P) and then Generate the Cassandra Workbench [You will see a .cassandraWorkbench folder and a .cassandraWorkbench.jsonc file being created]
3) Then go to the extension, open the CQL and run your queries.

**Comment by venkataphaniv** [comment]
Hi,

Cassandra Workbench needs a folder in which the .cassandraWorkbench.jsonc file can be created and placed. There are two approaches to resolve the issue:

a.open a code folder / any working folder where the .cassandraWorkbench.jsonc file can be placed (note - this file is created in the main folder itself)

2. create a .cassandraWorkbench.jsonc file using any editor and place the following in it:

[
    // AllowAllAuthenticator
    {
        "name": "Cluster AllowAllAuthenticator",
        "contactPoints": ["127.0.0.1"]
    }
    // ,
    //PasswordAuthenticator
    // {
    //     "name": "Cluster PasswordAuthenticator",
    //     "contactPoints": ["127.0.0.1"],
    //     "authProvider": {
    //         "class": "PasswordAuthenticator",
    //         "username": "yourUsername",
    //         "password": "yourPassword"
    //     }
    // }
]

PS: I've commented authentication based connection properties as it's not applicable in my case

When you place this file in any folder and open it in vscode, you can see that the Cassandra workbench loads automatically and lists the keyspaces
